import type { NetworkPageContent } from '~~/types/network'

export const networkContent: NetworkPageContent = {
  status: 'draft',
  title: 'شبكتنا',
  description: 'اكتشف قنوات توزيع بنزوما في المملكة العربية السعودية: الصيدليات والتجارة الإلكترونية والمستشفيات وتجار الجملة ومتاجر مستحضرات التجميل.',
  eyebrow: 'روابط يصنعها التوزيع',
  intro: 'نربط العلامات التجارية بالقنوات التي تخدم السوق السعودي.',
  channelsHeading: 'قنوات متنوعة. وسوق يجمعنا.',
  channelsLabel: 'اكتشف قنوات عملائنا',
  channels: [
    { id: 'pharmacies', name: 'الصيدليات', description: 'منتجات العناية بالجمال والصحة ضمن قناة البيع بالتجزئة في الصيدليات.' },
    { id: 'e-commerce', name: 'التجارة الإلكترونية', description: 'البيع عبر الإنترنت ضمن منظومة قنوات العملاء.' },
    { id: 'hospitals', name: 'المستشفيات', description: 'قنوات مشتريات المستشفيات وعملاء الرعاية الصحية.' },
    { id: 'wholesale', name: 'تجار الجملة', description: 'التوريد بين الشركات من خلال قنوات البيع بالجملة.' },
    { id: 'cosmetics-stores', name: 'متاجر مستحضرات التجميل', description: 'متاجر متخصصة في بيع منتجات الجمال ومستحضرات التجميل.' },
  ],
  reach: {
    heading: 'شبكة تتحدد بالعملاء الذين تخدمهم.',
    body: 'تربط بنزوما علامات العناية بالجمال والصحة بقنوات العملاء في المملكة العربية السعودية. وتجمع هذه القنوات الصيدليات والتجارة الرقمية والرعاية الصحية وتجارة الجملة والتجزئة المتخصصة ضمن شبكة توزيع واحدة.',
    note: 'هذه قنوات للعملاء والتوزيع، وليست مواقع مملوكة لبنزوما.',
  },
  partners: {
    heading: 'العملاء والشركاء',
    body: 'مجموعة مختارة من قنوات الصيدليات والتجارة الإلكترونية والرعاية الصحية وتجارة الجملة ومتاجر مستحضرات التجميل كما وردت في ملف الشركة.',
    pendingLabel: 'الأسماء بانتظار التأكيد',
    pendingBody: 'أسماء العملاء والشركاء وشعاراتهم بانتظار الاعتماد.',
    note: 'الشعارات معروضة كما وردت في ملف الشركة. إدراجها يعكس هذه القائمة فقط، وليس تحققًا مستقلًا من علاقة تجارية قائمة حاليًا.',
    names: [
      { name: 'Al-Dawaa', status: 'approved', logo: { src: '/logos/partners/al-dawaa.png', width: 184, height: 184 } },
      { name: 'Nahdi', status: 'approved', logo: { src: '/logos/partners/nahdi.png', width: 160, height: 160 } },
      { name: 'Whites', status: 'approved', logo: { src: '/logos/partners/whites.png', width: 150, height: 150 } },
      { name: 'Outlet Pharmacy', status: 'approved', logo: { src: '/logos/partners/outlet-pharmacy.png', width: 170, height: 168 } },
      { name: 'Watsons', status: 'approved', logo: { src: '/logos/partners/watsons.png', width: 150, height: 148 } },
      { name: 'Nice One', status: 'approved', logo: { src: '/logos/partners/nice-one.png', width: 158, height: 141 } },
      { name: 'Ninja', status: 'approved', logo: { src: '/logos/partners/ninja.png', width: 164, height: 153 } },
      { name: 'Boutiqaat', status: 'approved', logo: { src: '/logos/partners/boutiqaat.png', width: 164, height: 163 } },
      { name: 'Ounass', status: 'approved', logo: { src: '/logos/partners/ounass.png', width: 150, height: 148 } },
      { name: 'Dr. Sulaiman Al Habib', status: 'approved', logo: { src: '/logos/partners/dr-sulaiman-al-habib.png', width: 171, height: 168 } },
      { name: 'International Medical Center', status: 'approved', logo: { src: '/logos/partners/international-medical-center.png', width: 198, height: 191 } },
      { name: 'Specialized Medical Center', status: 'approved', logo: { src: '/logos/partners/specialized-medical-center.png', width: 182, height: 165 } },
      { name: 'Global Healthcare', status: 'approved', logo: { src: '/logos/partners/global-healthcare.png', width: 150, height: 148 } },
      { name: 'Wared Co.', status: 'approved', logo: { src: '/logos/partners/wared-co.png', width: 168, height: 169 } },
      { name: 'Dar Al-Amirat', status: 'approved', logo: { src: '/logos/partners/dar-alamirat.png', width: 134, height: 134 } },
      { name: 'NMA', status: 'approved', logo: { src: '/logos/partners/nma.png', width: 168, height: 171 } },
      { name: 'Makhazen Al-Enayah', status: 'approved', logo: { src: '/logos/partners/makhazen-alenayah.png', width: 166, height: 171 } },
      { name: 'Gold Apple', status: 'approved', logo: { src: '/logos/partners/gold-apple.png', width: 150, height: 150 } },
      { name: 'Badr Al-Alamiyah', status: 'approved', logo: { src: '/logos/partners/badr-alalamiyah.png', width: 150, height: 148 } },
      { name: 'Orange', status: 'approved', logo: { src: '/logos/partners/orange.png', width: 156, height: 161 } },
      { name: 'Saleh Cosmetics', status: 'approved', logo: { src: '/logos/partners/saleh-cosmetics.png', width: 141, height: 142 } },
      { name: 'Care Seasons', status: 'approved', logo: { src: '/logos/partners/care-seasons.png', width: 138, height: 135 } },
      { name: 'Nawaqis', status: 'approved', logo: { src: '/logos/partners/nawaqis.png', width: 157, height: 157 } },
      { name: 'Beauty Outlet', status: 'approved', logo: { src: '/logos/partners/beauty-outlet.png', width: 150, height: 148 } },
      { name: 'Dunia Al-Osra', status: 'approved', logo: { src: '/logos/partners/dunia-alosra.png', width: 150, height: 148 } },
    ],
  },
  enquiry: {
    heading: 'لنتحدث عن احتياجات قنواتك.',
    body: 'ابدأ حوارًا تجاريًا مع فريق بنزوما حول السوق السعودي.',
    cta: { label: 'ناقش استفسارك التجاري', to: '/contact' },
  },
}
