import type { NetworkPageContent } from '~~/types/network'

export const networkContent: NetworkPageContent = {
  status: 'draft',
  title: 'Our Network',
  description: 'Explore Binzomah’s distribution channels in Saudi Arabia: pharmacies, e-commerce, hospitals, wholesale and cosmetics stores.',
  eyebrow: 'Connected through distribution',
  intro: 'Connecting brands with the channels that serve the Saudi market.',
  channelsHeading: 'Different channels. A shared market.',
  channelsLabel: 'Explore our customer channels',
  channels: [
    { id: 'pharmacies', name: 'Pharmacies', description: 'Beauty and health care products within the pharmacy retail channel.' },
    { id: 'e-commerce', name: 'E-Commerce', description: 'Online retail as part of the customer-channel mix.' },
    { id: 'hospitals', name: 'Hospitals', description: 'Hospital purchasing and healthcare customer channels.' },
    { id: 'wholesale', name: 'Wholesale', description: 'Business-to-business supply through wholesale channels.' },
    { id: 'cosmetics-stores', name: 'Cosmetics Stores', description: 'Specialist beauty and cosmetics retailers.' },
  ],
  reach: {
    heading: 'A network defined by the customers it serves.',
    body: 'Binzomah connects beauty and health care brands with customer channels in Saudi Arabia. The channel mix brings pharmacy, digital, healthcare, wholesale and specialist retail into one distribution network.',
    note: 'These are customer and distribution channels, not locations owned by Binzomah.',
  },
  partners: {
    heading: 'Clients & partners',
    body: 'A selection of the pharmacy, e-commerce, healthcare, wholesale and cosmetics-store channels represented in Binzomah’s company profile.',
    pendingLabel: 'Names pending confirmation',
    pendingBody: 'Client and partner names and logos are awaiting approval.',
    note: 'Logos are reproduced as they appear in Binzomah’s company profile. Inclusion reflects that listing, not an independently reverified, current commercial relationship.',
    names: [
      { name: 'Al-Dawaa', status: 'approved', logo: { src: '/logos/partners/al-dawaa.png', width: 184, height: 184 } },
      { name: 'Nahdi', status: 'approved', logo: { src: '/logos/partners/nahdi.png', width: 160, height: 160 } },
      { name: 'Whites', status: 'approved', logo: { src: '/logos/partners/whites.png', width: 150, height: 150 } },
      { name: 'Outlet Pharmacy', status: 'approved', logo: { src: '/logos/partners/outlet-pharmacy.png', width: 170, height: 168 } },
      { name: 'Watsons', status: 'approved', logo: { src: '/logos/partners/watsons.png', width: 150, height: 148 } },
      { name: 'Nice One', status: 'approved', logo: { src: '/logos/partners/nice-one.png', width: 158, height: 141 } },
      { name: 'Ninja', status: 'approved', logo: { src: '/logos/partners/ninja.png', width: 164, height: 153 } },
      { name: 'Boutiqaat', status: 'approved', logo: { src: '/logos/partners/boutiqaat.png', width: 164, height: 163 } },
      { name: 'Ounass', status: 'approved', logo: { src: '/logos/partners/ounass.png', width: 150, height: 148 } },
      { name: 'Dr. Sulaiman Al Habib', status: 'approved', logo: { src: '/logos/partners/dr-sulaiman-al-habib.png', width: 171, height: 168 } },
      { name: 'International Medical Center', status: 'approved', logo: { src: '/logos/partners/international-medical-center.png', width: 198, height: 191 } },
      { name: 'Specialized Medical Center', status: 'approved', logo: { src: '/logos/partners/specialized-medical-center.png', width: 182, height: 165 } },
      { name: 'Global Healthcare', status: 'approved', logo: { src: '/logos/partners/global-healthcare.png', width: 150, height: 148 } },
      { name: 'Wared Co.', status: 'approved', logo: { src: '/logos/partners/wared-co.png', width: 168, height: 169 } },
      { name: 'Dar Al-Amirat', status: 'approved', logo: { src: '/logos/partners/dar-alamirat.png', width: 134, height: 134 } },
      { name: 'NMA', status: 'approved', logo: { src: '/logos/partners/nma.png', width: 168, height: 171 } },
      { name: 'Makhazen Al-Enayah', status: 'approved', logo: { src: '/logos/partners/makhazen-alenayah.png', width: 166, height: 171 } },
      { name: 'Gold Apple', status: 'approved', logo: { src: '/logos/partners/gold-apple.png', width: 150, height: 150 } },
      { name: 'Badr Al-Alamiyah', status: 'approved', logo: { src: '/logos/partners/badr-alalamiyah.png', width: 150, height: 148 } },
      { name: 'Orange', status: 'approved', logo: { src: '/logos/partners/orange.png', width: 156, height: 161 } },
      { name: 'Saleh Cosmetics', status: 'approved', logo: { src: '/logos/partners/saleh-cosmetics.png', width: 141, height: 142 } },
      { name: 'Care Seasons', status: 'approved', logo: { src: '/logos/partners/care-seasons.png', width: 138, height: 135 } },
      { name: 'Nawaqis', status: 'approved', logo: { src: '/logos/partners/nawaqis.png', width: 157, height: 157 } },
      { name: 'Beauty Outlet', status: 'approved', logo: { src: '/logos/partners/beauty-outlet.png', width: 150, height: 148 } },
      { name: 'Dunia Al-Osra', status: 'approved', logo: { src: '/logos/partners/dunia-alosra.png', width: 150, height: 148 } },
    ],
  },
  enquiry: {
    heading: 'Let’s talk about your channel needs.',
    body: 'Start a commercial conversation with the Binzomah team about the Saudi market.',
    cta: { label: 'Discuss a commercial enquiry', to: '/contact' },
  },
}
